services:
    backend:
        restart: always
        build: ./server
        ports:
            - "8000:8000"
        command: npm run dev
        container_name: circleconnect_backend
        volumes:
            - node_modules_backend:/home/server/node_modules
            - ./server:/home/server
        depends_on:
            - db
    frontend:
        restart: always
        build: ./client
        ports:
            - "5173:5173"
        command: npm run dev
        container_name: circleconnect_frontend
        volumes:
            - node_modules_frontend:/home/client/node_modules
            - ./client:/home/client
        environment:
            - WDS_SOCKET_HOST=127.0.0.1
            - CHOKIDAR_USEPOLLING=true
            - WATCHPACK_POLLING=true
        depends_on:
            - backend
    db:
        restart: always
        image: postgres
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: root
            POSTGRES_DB: Circle
        volumes:
            - local_pgdata:/var/lib/postgresql/data
    # pgadmin:
    #     image: dpage/pgadmin4
    #     ports:
    #         - 5050:80
    #     environment:
    #         PGADMIN_DEFAULT_EMAIL: admin@admin.com
    #         PGADMIN_DEFAULT_PASSWORD: root
    #     volumes:
    #         - pgadmin-data:/var/lib/pgadmin
    #     networks:
    #         - app-network
    #     links:
    #         - db
volumes:
    app-data:
        driver: local
    local_pgdata:
    pgadmin-data:
    node_modules_backend:
    node_modules_frontend:
